### ISSUE TITLE
Cover only test files

### ISSUE THREAD

**Issue by Lughino** [douglasduteil/isparta#114]
I don't understand why isparta only cover test files.
This is my command:
```bash
babel-node node_modules/.bin/isparta cover -v --report lcov --report html node_modules/mocha/bin/_mocha -- --compilers js:babel-register --recursive "client/**/*.test.js" "common/**/*.test.js" "server/**/*.test.js"
```

This is verbose output:

```yml
Using configuration
-------------------
verbose: true
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: []
    embed-source: false
    variable: __coverage__
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
    baseline-file: ./coverage/coverage-baseline.json
    include-all-sources: false
    include-pid: false
    es-modules: false
    preload-sources: false
reporting:
    print: summary
    reports:
        - lcov
        - html
    dir: ./coverage
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
    report-config:
        clover: {file: clover.xml}
        cobertura: {file: cobertura-coverage.xml}
        json: {file: coverage-final.json}
        json-summary: {file: coverage-summary.json}
        lcovonly: {file: lcov.info}
        teamcity: {file: null, blockName: Code Coverage Summary}
        text: {file: null, maxCols: 0}
        text-lcov: {file: lcov.info}
        text-summary: {file: null}
hooks:
    hook-run-in-context: false
    post-require-hook: null
    handle-sigint: false
check:
    global:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
    each:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []

-------------------

Isparta options : 
  { '0': 'cover',
  '--': 
   [ '--compilers',
     'js:babel-register',
     '--recursive',
     'client/**/*.test.js',
     'common/**/*.test.js',
     'server/**/*.test.js' ],
  verbose: true,
  report: [ 'lcov', 'html' ],
  cmd: 'node_modules/mocha/bin/_mocha',
  _: [ 'cover', 'node_modules/mocha/bin/_mocha' ],
  excludes: [],
  include: [ '**/*.js', 'node_modules/mocha/bin/_mocha' ] }
Running: node /src/node_modules/mocha/bin/_mocha --compilers js:babel-register --recursive client/**/*.test.js common/**/*.test.js server/**/*.test.js
Module load hook: transform [/src/client/client.test.js]
Module load hook: transform [/src/common/common.test.js]
Module load hook: transform [/src/server/server.test.js]

```
